name: Create Resource
description: 'Creates an OpenAI resource in Azure'

inputs:
  rgName:
    description: 'Name of the resource group to deploy to'
    required: true
  location:
    description: 'Location of the resource group to deploy to'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create RG
      id: jobRun
      shell: bash
      run: |
        az cognitiveservices account create --name ${{ inputs.rgName }} --location ${{ inputs.location }} --kind OpenAI --sku S0