name: azure login
description: 'Login to Azure using environment variables.'

runs:
  using: "composite"
  steps:
    - name: Login to Azure with SP
      id: jobRun
      shell: bash
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}